"""'role_fix'

Revision ID: 39ef9d9affaf
Revises: ab1b990bb806
Create Date: 2024-03-25 22:52:04.182477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39ef9d9affaf'
down_revision: Union[str, None] = 'ab1b990bb806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM(name='user_role_enum'),
               type_=sa.Enum('ADMIN', 'MODER', 'USER', name='userroles'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MODER', 'USER', name='userroles'),
               type_=postgresql.ENUM(name='user_role_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
