"""Збільшення довжини для title в Photo

Revision ID: 62a5f9bdc329
Revises: 7dba1d2d6d63
Create Date: 2024-03-29 12:26:32.488400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a5f9bdc329'
down_revision: Union[str, None] = '7dba1d2d6d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # commands auto generated by Alembic - please adjust!
    op.alter_column('photos', 'title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)
    # end Alembic commands



def downgrade():
    # commands auto generated by Alembic - please adjust!
    op.alter_column('photos', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    # end Alembic commands

