"""'add_banned'

Revision ID: df2af4b26bfb
Revises: 7dba1d2d6d63
Create Date: 2024-03-29 20:24:45.687645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2af4b26bfb'
down_revision: Union[str, None] = '7dba1d2d6d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tags', ['name'])
    op.add_column('users', sa.Column('banned', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    op.drop_constraint(None, 'tags', type_='unique')
    # ### end Alembic commands ###
